indent_type = "Spaces"
indent_width = 4
column_width = 120
quote_style = "AutoPreferDouble"
line_endings = "Unix"
collapse_simple_statement = "Never"   # "Always", "Never", ou "FunctionOnly"

# Options supplémentaires
no_call_parentheses = false           # true/false supprime les parenthèses autour des appels de fonction avec un seul argument littéral

[sort_requires]
enabled = false

space_after_function_names = "None"  # None/Always ajoute un espace entre le nom de fonction et la parenthèse