name: Lua Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Lua and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 luarocks liblua5.3-dev

      - name: Install Luacheck (local)
        run: |
          luarocks install --local luacheck
          echo "$HOME/.luarocks/bin" >> $GITHUB_PATH

      - name: Run Luacheck
        run: luacheck .

name: Lua Format

on: [push, pull_request]

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Stylua
        run: |
          curl -L https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux.zip -o stylua.zip
          unzip stylua.zip -d stylua-bin
          sudo mv stylua-bin/stylua /usr/local/bin/stylua

      - name: Run Stylua check
        run: stylua --check .