name: Lua Format

on: [push, pull_request]

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Stylua
        run: cargo install stylua --locked
        
      - name: Run Stylua check - Core
        run: stylua --check Core/
      
      - name: Run Stylua check - Data
        run: stylua --check Data/
      
      - name: Run Stylua check - Features
        run: stylua --check Features/
      
      - name: Run Stylua check - UI
        run: stylua --check UI/
        
      - name: Run Stylua check - Locales
        run: stylua --check Locales/
        
      - name: Run Stylua check - Strategies
        run: stylua --check Strategies/